#ifndef TSPISRAMHARDWARE_H
#define TSPISRAMHARDWARE_H
/*----------------------------------------------------------------------------------*/

#define SPISRAM_ADDR_SIZE		3
#define SPISRAM_PAGE_SIZE		32

#define SPISRAM_GPIO_RCC_ENABLE		RCC_AHBPeriphClockCmd(RCC_AHBPeriph_GPIOB, ENABLE)
#define SPISRAM_SPI_RCC_ENABLE		RCC_APB2PeriphClockCmd( RCC_APB2Periph_SPI1, ENABLE )
#define SPISRAM_CS_PORT			GPIOB
#define SPISRAM_CS_PIN			GPIO_Pin_8
#define SPISRAM_SCK_PORT		GPIOB
#define SPISRAM_SCK_PIN			GPIO_Pin_3
#define SPISRAM_SCK_PINSOURCE		GPIO_PinSource3
#define SPISRAM_MISO_PORT		GPIOB
#define SPISRAM_MISO_PIN		GPIO_Pin_4
#define SPISRAM_MISO_PINSOURCE		GPIO_PinSource4
#define SPISRAM_MOSI_PORT		GPIOB
#define SPISRAM_MOSI_PIN		GPIO_Pin_5
#define SPISRAM_MOSI_PINSOURCE		GPIO_PinSource5
#define SPISRAM_SPI			SPI1
#define SPISRAM_SPI_AF			GPIO_AF_0
#define SPISRAM_IRQ_PORT		GPIOB
#define SPISRAM_IRQ_PIN			GPIO_Pin_9

#define SPISRAM_LOWSIDE

#endif //TSPISRAMHARDWARE_H